"""
Vendra Supplier Catalog Seed (backend/app/database/seed.py)
Seeds 12 high-quality Indian illustrative manufacturing suppliers (prioritizing Bengaluru & Karnataka).
All monetary values are in INR (₹). Fictional suppliers are explicitly marked demo_supplier=1
and evidence='Illustrative demo data' as mandated by Sections 17, 22, and 62.
"""
from app.database.base import utc_now_iso
from app.database.session import get_db, run_migrations


ILLUSTRATIVE_SUPPLIERS = [
    {
        "supplier_id": "sup_peenya_01",
        "name": "Demo Supplier A — Kaveri EcoPack & Drinkware Works (Illustrative)",
        "location": "Peenya Industrial Area, Stage II, Bengaluru, Karnataka",
        "area": "Peenya",
        "city": "Bengaluru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Reusable bottles, stainless steel insulated flasks, bamboo-lid bottles, laser engraving, custom consumer vessels",
        "materials": "SS 304 Food-Grade Steel, Recycled Stainless Steel, Bamboo, BPA-Free Silicone, Copper-lined Steel",
        "minimum_order_quantity": 500,
        "indicative_unit_price_inr": 255.0,
        "lead_time_days": 22,
        "certifications": "ISO 9001:2015, BIS IS 14756, FSSAI Food Contact Safe",
        "packaging_capabilities": "FSC Kraft Cylinder Tubes, Molded Pulp Inserts, Custom Monochrome Sleeves",
        "payment_terms": "30% Advance, 70% Pre-Dispatch (NEFT/RTGS)",
        "shipping_regions": "Bengaluru, Karnataka, South India, Pan-India Surface",
        "reliability_score": 94.0,
        "evidence": "Illustrative demo data — Peenya Cluster Tier-1 Benchmark",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_bommasandra_02",
        "name": "Demo Supplier B — Dakshin HydroVessels & Molding Pvt Ltd (Illustrative)",
        "location": "Bommasandra Industrial Area, Hosur Road, Bengaluru, Karnataka",
        "area": "Bommasandra",
        "city": "Bengaluru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Eco-friendly reusable bottles, double-wall vacuum bottles, bamboo lunch boxes, injection & blow forming",
        "materials": "SS 304 Food-Grade Steel, Bamboo Fiber Composite, Recycled Aluminum, Borosilicate Glass",
        "minimum_order_quantity": 500,
        "indicative_unit_price_inr": 248.0,
        "lead_time_days": 25,
        "certifications": "ISO 9001:2015, ISO 14001, BIS Certified, SEDEX",
        "packaging_capabilities": "Recycled Corrugated Cartons, Individual Kraft Boxes, Barcode Labelling",
        "payment_terms": "25% Advance, 75% on Quality Inspection",
        "shipping_regions": "Bengaluru, Karnataka, Tamil Nadu, Pan-India",
        "reliability_score": 89.0,
        "evidence": "Illustrative demo data — Bommasandra Industrial Directory",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_jigani_03",
        "name": "Demo Supplier C — Nandi GreenWare & Bamboo Craft Industries (Illustrative)",
        "location": "Jigani Industrial Area, Anekal Taluk, Bengaluru, Karnataka",
        "area": "Jigani",
        "city": "Bengaluru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Bamboo lunch boxes, eco-friendly reusable bottles, bento meal containers, sustainable tableware, compression molding",
        "materials": "Treated Moso Bamboo, Bamboo Fiber, SS 304 Inner Liners, Food-Grade Silicone Seals",
        "minimum_order_quantity": 400,
        "indicative_unit_price_inr": 182.0,
        "lead_time_days": 21,
        "certifications": "ISO 9001:2015, FSSAI Compliant, FSC Chain-of-Custody, RoHS",
        "packaging_capabilities": "Zero-Plastic Kraft Belly Bands, Compostable Shrink Wrap, Master Export Cartons",
        "payment_terms": "30% Advance, 70% on Dispatch",
        "shipping_regions": "Bengaluru, Karnataka, Pan-India",
        "reliability_score": 95.0,
        "evidence": "Illustrative demo data — Jigani Eco-Manufacturing Cluster",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_yeshwanthpur_04",
        "name": "Demo Supplier D — Sahyadri Precision Metals & Containers (Illustrative)",
        "location": "Yeshwanthpur Industrial Suburb, Tumkur Road, Bengaluru, Karnataka",
        "area": "Yeshwanthpur",
        "city": "Bengaluru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Stainless steel lunch boxes, reusable bottles, insulated tumblers, deep drawing & hydroforming, powder coating",
        "materials": "SS 304 Food-Grade Steel, SS 316 Surgical Grade, Bamboo Caps, Natural Cork",
        "minimum_order_quantity": 750,
        "indicative_unit_price_inr": 262.0,
        "lead_time_days": 24,
        "certifications": "ISO 9001:2015, BIS IS 14756, ZED Silver MSME",
        "packaging_capabilities": "Die-Cut Corrugated Retail Boxes, Custom Foil Stamping, Palletized Dispatch",
        "payment_terms": "40% Advance, 60% against Delivery Challan",
        "shipping_regions": "Bengaluru, Karnataka, Maharashtra, Pan-India",
        "reliability_score": 92.0,
        "evidence": "Illustrative demo data — Yeshwanthpur MSME Registry",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_rajajinagar_05",
        "name": "Demo Supplier E — Vrishabhavathi Corporate Kits & Merch Studio (Illustrative)",
        "location": "Rajajinagar Industrial Estate, West of Chord Road, Bengaluru, Karnataka",
        "area": "Rajajinagar",
        "city": "Bengaluru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Custom office merchandise, onboarding welcome kits, cork notebooks, bamboo desk organizers, branded drinkware kitting",
        "materials": "Recycled Cotton Canvas, Cork, Bamboo, Recycled Paperboard, SS 304 Drinkware",
        "minimum_order_quantity": 200,
        "indicative_unit_price_inr": 235.0,
        "lead_time_days": 16,
        "certifications": "ISO 9001:2015, GRS Global Recycled Standard, MSME Udyam Verified",
        "packaging_capabilities": "Rigid Magnetic Gift Boxes, Custom Printed Kraft Mailers, Kitting & Fulfillment",
        "payment_terms": "30% Advance, 70% prior to Dispatch",
        "shipping_regions": "Bengaluru Intra-City, Karnataka, Pan-India Courier",
        "reliability_score": 93.0,
        "evidence": "Illustrative demo data — Rajajinagar Industrial Estate",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_whitefield_06",
        "name": "Demo Supplier F — Mahadevapura Sustainable Packaging & Kits (Illustrative)",
        "location": "Whitefield Industrial Corridor, Hoodi, Bengaluru, Karnataka",
        "area": "Whitefield",
        "city": "Bengaluru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Custom office kits, sustainable packaging boxes, bamboo lunch boxes, corporate gift assemblies, UV screen printing",
        "materials": "Bamboo, Kraft Board, Recycled PET Felt, Organic Cotton, Food-Grade Steel",
        "minimum_order_quantity": 250,
        "indicative_unit_price_inr": 190.0,
        "lead_time_days": 18,
        "certifications": "ISO 9001:2015, FSC Certified, ISO 14001",
        "packaging_capabilities": "Custom Rigid Boxes, Partitioned Kit Cartons, Eco Soy-Ink Printing",
        "payment_terms": "30% Advance, 70% Net 7 Days",
        "shipping_regions": "Bengaluru East, Karnataka, Pan-India",
        "reliability_score": 91.0,
        "evidence": "Illustrative demo data — Whitefield Industrial Corridor",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_electronic_city_07",
        "name": "Demo Supplier G — Veerasandra CleanTech Polymers & Biocomposites (Illustrative)",
        "location": "Electronic City Phase II, Veerasandra Industrial Area, Bengaluru, Karnataka",
        "area": "Electronic City",
        "city": "Bengaluru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Bamboo fiber lunch boxes, bio-composite reusable bottles, reusable coffee cups, ultrasonic welding",
        "materials": "Bamboo Fiber Biocomposite, PLA Bio-Resin, Rice Husk Composite, Food-Grade Silicone",
        "minimum_order_quantity": 500,
        "indicative_unit_price_inr": 175.0,
        "lead_time_days": 19,
        "certifications": "ISO 9001:2015, CIPET Tested Compostable, FSSAI Food Contact",
        "packaging_capabilities": "Compostable Bagasse Trays, Recycled Kraft Sleeves, Bulk Cartons",
        "payment_terms": "25% Advance, 75% Pre-Shipment",
        "shipping_regions": "Bengaluru South, Karnataka, Tamil Nadu, Pan-India",
        "reliability_score": 96.0,
        "evidence": "Illustrative demo data — Veerasandra Biopolymer Cluster",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_peenya_08",
        "name": "Demo Supplier H — Tungabhadra Sheet Metal & Bottle Works (Illustrative)",
        "location": "Peenya Industrial Area, Stage IV, Bengaluru, Karnataka",
        "area": "Peenya",
        "city": "Bengaluru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Reusable bottles, copper & steel water bottles, lunch tiffin carriers, anodizing and brushing",
        "materials": "SS 304 Steel, Pure Copper 99.7%, Bamboo Tops, Silicone Grips",
        "minimum_order_quantity": 1000,
        "indicative_unit_price_inr": 268.0,
        "lead_time_days": 27,
        "certifications": "ISO 9001:2015, BIS Certified",
        "packaging_capabilities": "Standard Corrugated Boxes, Bubble-Free Honeycomb Wrap",
        "payment_terms": "50% Advance, 50% on Dispatch",
        "shipping_regions": "Bengaluru, Karnataka, South India",
        "reliability_score": 87.0,
        "evidence": "Illustrative demo data — Peenya Stage IV Cluster",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_mysuru_09",
        "name": "Demo Supplier I — Hebbal Mysuru Eco-Timber & Bamboo Works (Illustrative)",
        "location": "Hebbal Industrial Area, Mysuru, Karnataka",
        "area": "Hebbal Industrial Area",
        "city": "Mysuru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Artisanal & CNC bamboo lunch boxes, wooden desk accessories, bamboo bottle shells, natural food-safe lacquer",
        "materials": "Seasoned Karnataka Bamboo, Acacia Wood, Beeswax Food-Safe Coating, SS 304 Inserts",
        "minimum_order_quantity": 300,
        "indicative_unit_price_inr": 188.0,
        "lead_time_days": 23,
        "certifications": "ISO 9001:2015, FSC 100%, GI Craft Certified",
        "packaging_capabilities": "Jute Pouches, Recycled Kraft Boxes, Edge-Protected Master Cartons",
        "payment_terms": "30% Advance, 70% on Dispatch",
        "shipping_regions": "Mysuru, Bengaluru, Karnataka, Pan-India",
        "reliability_score": 93.0,
        "evidence": "Illustrative demo data — Mysuru Hebbal Industrial Zone",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_hosur_10",
        "name": "Demo Supplier J — SIPCOT Precision Consumer Manufacturing (Illustrative)",
        "location": "SIPCOT Industrial Complex, Phase I, Hosur, Tamil Nadu",
        "area": "SIPCOT Phase I",
        "city": "Hosur",
        "state": "Tamil Nadu",
        "manufacturing_capabilities": "High-volume reusable bottles, vacuum flasks, insulated food jars, automated powder coating line",
        "materials": "SS 304 Steel, SS 201 Outer Shell, Polypropylene BPA-Free Lids",
        "minimum_order_quantity": 1500,
        "indicative_unit_price_inr": 240.0,
        "lead_time_days": 28,
        "certifications": "ISO 9001:2015, ISO 45001, BIS IS 14756",
        "packaging_capabilities": "Automated Shrink & Carton Line, Export Palletization",
        "payment_terms": "30% Advance, 70% against B/L",
        "shipping_regions": "Bengaluru Border, Tamil Nadu, Karnataka, Pan-India",
        "reliability_score": 90.0,
        "evidence": "Illustrative demo data — Hosur SIPCOT Corridor",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_coimbatore_11",
        "name": "Demo Supplier K — Kovai Sustainable Textiles & Office Kits (Illustrative)",
        "location": "SIDCO Industrial Estate, Kurichi, Coimbatore, Tamil Nadu",
        "area": "SIDCO Kurichi",
        "city": "Coimbatore",
        "state": "Tamil Nadu",
        "manufacturing_capabilities": "Custom office merchandise, organic cotton tote bags, apparel & drinkware kits, embroidery & screen print",
        "materials": "GOTS Organic Cotton, Recycled Polyester, Canvas, Bamboo Accessories",
        "minimum_order_quantity": 250,
        "indicative_unit_price_inr": 215.0,
        "lead_time_days": 20,
        "certifications": "ISO 9001:2015, GOTS Certified, OEKO-TEX Standard 100",
        "packaging_capabilities": "Compostable Cornstarch Mailers, Kraft Gift Boxes",
        "payment_terms": "30% Advance, 70% before Dispatch",
        "shipping_regions": "Tamil Nadu, Karnataka, Bengaluru, Pan-India",
        "reliability_score": 92.0,
        "evidence": "Illustrative demo data — Coimbatore SIDCO Cluster",
        "demo_supplier": 1,
    },
    {
        "supplier_id": "sup_peenya_12",
        "name": "Demo Supplier L — Deccan Rapid-Proto & Short-Run Works (Illustrative)",
        "location": "Peenya Industrial Area, 1st Stage, Bengaluru, Karnataka",
        "area": "Peenya",
        "city": "Bengaluru",
        "state": "Karnataka",
        "manufacturing_capabilities": "Low-MOQ custom office kits, bamboo lunch boxes, laser-etched reusable bottles, rapid batch manufacturing",
        "materials": "Bamboo, SS 304 Steel, Anodized Aluminum, Recycled Acrylic, Kraft",
        "minimum_order_quantity": 100,
        "indicative_unit_price_inr": 265.0,
        "lead_time_days": 14,
        "certifications": "ISO 9001:2015, MSME ZED Bronze",
        "packaging_capabilities": "Custom Short-Run Digital Printed Boxes, Foam-Free Inserts",
        "payment_terms": "50% Advance, 50% on Delivery",
        "shipping_regions": "Bengaluru Same-Day, Karnataka, Pan-India",
        "reliability_score": 94.0,
        "evidence": "Illustrative demo data — Peenya Rapid-Batch Directory",
        "demo_supplier": 1,
    },
]


def seed_suppliers_catalog() -> None:
    run_migrations()
    now = utc_now_iso()
    with get_db() as conn:
        for sup in ILLUSTRATIVE_SUPPLIERS:
            conn.execute(
                """
                INSERT INTO suppliers (
                    supplier_id, name, location, area, city, state,
                    manufacturing_capabilities, materials, minimum_order_quantity,
                    indicative_unit_price_inr, lead_time_days, certifications,
                    packaging_capabilities, payment_terms, shipping_regions,
                    reliability_score, evidence, demo_supplier, created_at, updated_at
                ) VALUES (
                    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
                )
                ON CONFLICT(supplier_id) DO UPDATE SET
                    name = excluded.name,
                    location = excluded.location,
                    area = excluded.area,
                    city = excluded.city,
                    state = excluded.state,
                    manufacturing_capabilities = excluded.manufacturing_capabilities,
                    materials = excluded.materials,
                    minimum_order_quantity = excluded.minimum_order_quantity,
                    indicative_unit_price_inr = excluded.indicative_unit_price_inr,
                    lead_time_days = excluded.lead_time_days,
                    certifications = excluded.certifications,
                    packaging_capabilities = excluded.packaging_capabilities,
                    payment_terms = excluded.payment_terms,
                    shipping_regions = excluded.shipping_regions,
                    reliability_score = excluded.reliability_score,
                    evidence = excluded.evidence,
                    demo_supplier = excluded.demo_supplier,
                    updated_at = excluded.updated_at
                """,
                (
                    sup["supplier_id"],
                    sup["name"],
                    sup["location"],
                    sup["area"],
                    sup["city"],
                    sup["state"],
                    sup["manufacturing_capabilities"],
                    sup["materials"],
                    sup["minimum_order_quantity"],
                    sup["indicative_unit_price_inr"],
                    sup["lead_time_days"],
                    sup["certifications"],
                    sup["packaging_capabilities"],
                    sup["payment_terms"],
                    sup["shipping_regions"],
                    sup["reliability_score"],
                    sup["evidence"],
                    sup["demo_supplier"],
                    now,
                    now,
                ),
            )
